# Generated by Django 5.1.3 on 2025-01-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.AlterModelOptions(
            name='anamnesis',
            options={'verbose_name': 'Anamnese', 'verbose_name_plural': 'Anamneses'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='userblock',
            options={'verbose_name': 'Bloqueio', 'verbose_name_plural': 'Bloqueios'},
        ),
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'verbose_name': 'Seguidor', 'verbose_name_plural': 'Seguidores'},
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentário'), ('light', 'Leve'), ('moderate', 'Moderado'), ('active', 'Ativo'), ('very_active', 'Muito Ativo')], max_length=50, verbose_name='Nível de Atividade'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='available_days',
            field=models.CharField(max_length=200, verbose_name='Dias Disponíveis'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='goals',
            field=models.TextField(verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='injury_history',
            field=models.TextField(blank=True, verbose_name='Histórico de Lesões'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='medical_restrictions',
            field=models.TextField(blank=True, verbose_name='Restrições Médicas'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fitness_goals',
            field=models.TextField(blank=True, max_length=500, verbose_name='Objetivos Fitness'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Aluno'), ('trainer', 'Personal'), ('admin', 'Admin')], default='student', max_length=10, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Bloqueado'),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Seguindo'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
