# Generated by Django 5.1.3 on 2025-01-06 15:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.profile_picture_path, verbose_name='Foto de Perfil'),
        ),
    ]
