# Generated by Django 5.1.3 on 2025-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color_palette',
            field=models.CharField(choices=[('default', 'Padrão - Azul Energia'), ('nature', 'Verde Natureza'), ('sunset', 'Pôr do Sol'), ('ocean', 'Oceano Profundo'), ('berry', 'Frutas Silvestres'), ('monochrome', 'Monocromático')], default='default', max_length=20, verbose_name='Paleta de Cores'),
        ),
    ]
